version: '3'
services:
  game-server:
    container_name: gwynedd-valley
    image: gwynedd-valley:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: unless-stopped
    hostname: game-server
    environment:
      - TZ=America/New_York
      # - MONGODB_URI=mongodb://mongodbserver:27017
    ports:
      - "3000:3000/tcp"
    volumes:
      - gwynedd-valley:/mnt/gv-data/
    logging: 
      driver: json-file
      options:
        max-size: "12m"
        max-file: "5"

volumes: 
  gwynedd-valley: